serviceAccount: 'bilinggrok-linebot@bilingrok.iam.gserviceaccount.com'

substitutions:
  _DEBUG_MODE: 'False'
  _SECRET_KEY_ENV: 'GCP'
  _ENVIRONMENT: 'PROD'
  _GCP_PROJECT_ID: 'bilingrok'
  _SERVICE_ACCOUNT_NAME: 'bilinggrok-linebot'
  _SERVICE_ACCOUNT_DESCRIPTION: 'Handle Line Bot Webhook Events'
  _SERVICE_ACCOUNT_DISPLAY_NAME: 'bilinggrok-linebot'
  _GCP_SA_SECRET_FILE: 'config/sa-linebot@bilingrok.iam.gserviceaccount.com.json'
  _DB_NAME: 'bilingrok'
  _WORK_DIR: '.'
  _IMAGE_NAME: 'bilingrok'
  _IMAGE_VERSION: 'v0.0.1'
  _DOCKERFILE_PATH: '.'
  _DOCKERFILE_NAME: 'Dockerfile'
  _GCP_COMPUTE_TYPE: 'cloud-run'
  _CONTAINER_NAME: 'bilingrok'
  _CONTAINER_REGION: 'asia-east1'
  _HOST_PORT: '5000'
  _CONTAINER_PORT: '5000'
  _ALLOW_UNAUTHENTICATED: 'allow-unauthenticated'
  _ENV_FILE: 'config/.env'
  _REPO_NAME: 'bilingrok'
  _GITHUB_USER_NAME: 'JustinRHHsu'
  _CLOUD_BUILD_TRIGGER_REGION: 'us-central1'
  _BRANCH_NAME: 'main'
  _BUILD_CONFIG_FILE: 'cloudbuild.yaml'
  _EVENT_TYPE: 'push'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _NUMBER_OF_MESSASES_FROM_CHAT_HISTORY: '10'
  _MESSAGES_FOR_REVIEW_LEARNING_CARD: '10'
# 這裡的變數是從 config/config.yaml 中取得的
   
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build App'
    dir: '${_WORK_DIR}'
    args: [
      'build',
      '-t', 'gcr.io/${_GCP_PROJECT_ID}/${_IMAGE_NAME}:$COMMIT_SHA',
      '-f', '${_DOCKERFILE_NAME}',
      '${_DOCKERFILE_PATH}'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push App'
    args: [
      'push',
      'gcr.io/${_GCP_PROJECT_ID}/${_IMAGE_NAME}:$COMMIT_SHA'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy App'
    entrypoint: bash
    args: [
      '-c',
      'gcloud run deploy ${_CONTAINER_NAME} \
      --image=gcr.io/${_GCP_PROJECT_ID}/${_IMAGE_NAME}:$COMMIT_SHA \
      --region=${_CONTAINER_REGION} \
      --platform managed \
      --${_ALLOW_UNAUTHENTICATED} \
      --port=${_CONTAINER_PORT} \
      --service-account="bilinggrok-linebot@bilingrok.iam.gserviceaccount.com" \
      --min-instances=${_MIN_INSTANCES} \
      --max-instances=${_MAX_INSTANCES}'
    ]
    secretEnv: ['LINE_CHANNEL_ACCESS_TOKEN','LINE_CHANNEL_SECRET','XAI_API_KEY']  
# 從 .env 檔案中取得 secretEnv 並且傳遞到 cloudbuild.yaml

images:
  - 'gcr.io/${_GCP_PROJECT_ID}/${_IMAGE_NAME}:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager: 
    - versionName: projects/$PROJECT_ID/secrets/LINE_CHANNEL_ACCESS_TOKEN/versions/latest
      env: 'LINE_CHANNEL_ACCESS_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/LINE_CHANNEL_SECRET/versions/latest
      env: 'LINE_CHANNEL_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/XAI_API_KEY/versions/latest
      env: 'XAI_API_KEY'  
# 從 .env 檔案中取得 secretManager 並且傳遞到 cloudbuild.yaml
    