# 執行環境參數
DEBUG_MODE: False
# True, False
SECRET_KEY_ENV: GCP
# GCP, LOCAL
ENVIRONMENT: PROD
# DEV, PROD

# GCP 設置參數
GCP_PROJECT_ID: bilingrok
SERVICE_ACCOUNT_NAME: bilingrok-linebot
SERVICE_ACCOUNT_DESCRIPTION: Handle Line Bot Webhook Events
SERVICE_ACCOUNT_DISPLAY_NAME: bilingrok-linebot
GCP_SA_SECRET_FILE: config/bilingrok-64cb8b639621.json
# SERVICE_ACCOUNT: SERVICE_ACCOUNT_NAME@$GCP_PROJECT_ID.iam.gserviceaccount.com

# Database 設置參數
DB_NAME: bilingrok

# Docker Image 設定
WORK_DIR: "."
IMAGE_NAME: "bilingrok"
IMAGE_VERSION: "v0.0.1"
DOCKERFILE_PATH: "."
DOCKERFILE_NAME: "Dockerfile"

# Docker Container 設定

GCP_COMPUTE_TYPE: cloud-run
# Container Name shoule less 63 characters, lowercase, numbers and dash only
CONTAINER_NAME: "bilingrok-linebot-prod"
CONTAINER_REGION: 'asia-east1'
HOST_PORT: 5000
CONTAINER_PORT: 5000
ALLOW_AUTHENTICATED: "--allow-unauthenticated"
ENV_FILE: "config/.env"


# Cloud Build 參數
REPO_NAME: "bilingrok"
GITHUB_USER_NAME: "JustinRHHsu"
CLOUD_BUILD_TRIGGER_REGION: "us-central1"
BRANCH_NAME: "main"
BUILD_CONFIG_FILE: "cloudbuild.yaml"
EVENT_TYPE: "push"

# Cloud Run 參數
# MIN_INSTANCES: 0
# MAX_INSTANCES: 10


# 會話 Memory 參數
NUMBER_OF_MESSASES_FROM_CHAT_HISTORY: 10
MESSAGES_FOR_REVIEW_LEARNING_CARD: 10


# 路徑參數
FLEX_LIBRARY_PATH: "line_message_template/flex_library"
PROMPT_TEMPLATE_PATH: "prompts"
AGENT_CHARACTER_PATH: "prompts/agent_character"

# QUEUE_MESSAGE_STORE: line-msg-to-firestore
# QUEUE_LOCATION_MESSAGE_STORE: asia-east1
# Cloud Task
# TIME_SLOT_PROCESS_MESSAGES_TO_LLM: 5
# SESSION_EXPIRED_TIME: 600
