DEBUG_MODE: True        # True, False
SECRET_KEY_ENV: LOCAL     # GCP, LOCAL
ENVIRONMENT: DEV       # DEV, PROD
GCP_PROJECT_ID: bilingrok

LINEBOT_WEBHOOK_PORT: 5000

SERVICE_ACCOUNT_NAME: bilinggrok-linebot
SERVICE_ACCOUNT_DESCRIPTION: Handle Line Bot Webhook Events
SERVICE_ACCOUNT_DISPLAY_NAME: bilinggrok-linebot
GCP_SA_SECRET_FILE: config/sa-linebot@bilingrok.iam.gserviceaccount.com.json

NUMBER_OF_MESSASES_FROM_CHAT_HISTORY: 10
MESSAGES_FOR_REVIEW_LEARNING_CARD: 10

# QUEUE_MESSAGE_STORE: line-msg-to-firestore
# QUEUE_LOCATION_MESSAGE_STORE: asia-east1
# Cloud Task
# TIME_SLOT_PROCESS_MESSAGES_TO_LLM: 5
# SESSION_EXPIRED_TIME: 600
